# Тема “Вычисления с помощью Numpy”

## Задание 1

In [1]:
import numpy as np

In [14]:
a = np.array([
    [1, 2, 3, 3, 1],
    [6, 8, 11, 10, 7]
]).T
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

## Задание 2

In [36]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

In [42]:
a_centered_sp = a_centered[:, 0].dot(a_centered[:, 1].T)
a_centered_sp/(a_centered.shape[0] - 1)

2.0

## Задание 4

In [41]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

# Тема “Работа с данными в Pandas”

## Задание 1

In [43]:
import pandas as pd

In [88]:
authors = pd.DataFrame(np.array([
    [1, 2, 3],
    ['Тургенев', 'Чехов', 'Островский']
]).T)
authors.columns = ['author_id', 'author_name']
authors['author_id'] = authors['author_id'].astype(int)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [89]:
book = pd.DataFrame(np.array([
    [1, 1, 1, 2, 2, 3, 3],
    ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий',
     'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    [450, 300, 350, 500, 450, 370, 290]
]).T, columns=['author_id', 'book_title', 'price'])
book['author_id'] = book['author_id'].astype(int)
book['price'] = book['price'].astype(int)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задание 2

In [90]:
authors_price = authors.merge(book, on='author_id', how='left')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3

In [91]:
top5 = authors_price.sort_values(by='price', ascending=False).head(5)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Задание 4

In [93]:
authors_stat = authors_price.pivot_table(index='author_name', values='price', aggfunc=['max', 'min', 'mean'])
authors_stat

max   min        mean
            price price       price
author_name                        
Островский    370   290  330.000000
Тургенев      450   300  366.666667
Чехов         500   450  475.000000

## Задание 5

In [99]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [100]:
book_info = authors_price.pivot_table(index='author_name', columns='cover', values='price', aggfunc='sum')
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      NaN
Тургенев      650.0    450.0
Чехов           NaN    950.0

In [101]:
book_info.to_pickle('book_info.pkl')

In [102]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский    660.0      NaN
Тургенев      650.0    450.0
Чехов           NaN    950.0